import type { GlobalThemeOverrides } from 'naive-ui'
import type { AppPalette } from './palette'

export function createThemeOverrides(p: AppPalette): GlobalThemeOverrides {
  return {
    common: {
      baseColor: p.surface,
      bodyColor: p.surface,
      cardColor: p.surface,
      modalColor: p.surfaceElevated,
      popoverColor: p.surfaceElevated,
      tableColor: p.surface,
      invertedColor: p.text,
      hoverColor: p.surfaceHover,
      borderColor: p.border,
      dividerColor: p.divider,
      textColorBase: p.text,
      textColor1: p.text,
      textColor2: p.textSecondary,
      textColor3: p.textMuted,
      textColorDisabled: p.controlDisabledText,
      placeholderColor: p.textPlaceholder,
      placeholderColorDisabled: p.controlDisabledText,
      inputColor: p.surface,
      inputColorDisabled: p.controlDisabledSurface,
      buttonColor2: p.controlSurface,
      buttonColor2Hover: p.controlSurfaceHover,
      buttonColor2Pressed: p.controlSurfacePressed,
      primaryColor: p.primary,
      primaryColorHover: p.primaryHover,
      primaryColorPressed: p.primaryPressed,
      primaryColorSuppl: p.primarySuppl,
      successColor: p.success,
      successColorHover: p.successHover,
      successColorPressed: p.successPressed,
      infoColor: p.info,
      infoColorHover: p.infoHover,
      infoColorPressed: p.infoPressed,
      warningColor: p.warning,
      warningColorHover: p.warningHover,
      warningColorPressed: p.warningPressed,
      errorColor: p.error,
      errorColorHover: p.errorHover,
      errorColorPressed: p.errorPressed,
    },
    Button: {
      color: p.controlSurface,
      colorHover: p.controlSurfaceHover,
      colorPressed: p.controlSurfacePressed,
      colorFocus: p.controlSurfaceHover,
      colorDisabled: p.controlDisabledSurface,
      colorSecondary: p.controlSurface,
      colorSecondaryHover: p.controlSurfaceHover,
      colorSecondaryPressed: p.controlSurfacePressed,
      colorTertiary: p.controlSurface,
      colorTertiaryHover: p.controlSurfaceHover,
      colorTertiaryPressed: p.controlSurfacePressed,
      colorQuaternary: p.transparent,
      colorQuaternaryHover: p.controlSurfaceHover,
      colorQuaternaryPressed: p.controlSurfacePressed,
      textColor: p.text,
      textColorHover: p.textStrong,
      textColorPressed: p.textStrong,
      textColorFocus: p.textStrong,
      textColorDisabled: p.controlDisabledText,
      textColorText: p.text,
      textColorTextHover: p.textStrong,
      textColorTextPressed: p.textStrong,
      textColorTextFocus: p.textStrong,
      textColorTextDisabled: p.controlDisabledText,
      textColorGhost: p.text,
      textColorGhostHover: p.textStrong,
      textColorGhostPressed: p.textStrong,
      textColorGhostFocus: p.textStrong,
      textColorGhostDisabled: p.controlDisabledText,
      border: `1px solid ${p.border}`,
      borderHover: `1px solid ${p.borderHover}`,
      borderPressed: `1px solid ${p.textStrong}`,
      borderFocus: `1px solid ${p.textStrong}`,
      borderDisabled: `1px solid ${p.controlDisabledBorder}`,
      textColorPrimary: p.textInverse,
      textColorHoverPrimary: p.textInverse,
      textColorPressedPrimary: p.textInverse,
      textColorFocusPrimary: p.textInverse,
      textColorDisabledPrimary: p.controlDisabledText,
      textColorTextPrimary: p.text,
      textColorTextHoverPrimary: p.textStrong,
      textColorTextPressedPrimary: p.textStrong,
      textColorTextFocusPrimary: p.textStrong,
      textColorTextDisabledPrimary: p.controlDisabledText,
      colorPrimary: p.primary,
      colorHoverPrimary: p.primaryHover,
      colorPressedPrimary: p.primaryPressed,
      colorFocusPrimary: p.primaryHover,
      colorDisabledPrimary: p.controlDisabledSurface,
      borderPrimary: `1px solid ${p.primary}`,
      borderHoverPrimary: `1px solid ${p.primaryHover}`,
      borderPressedPrimary: `1px solid ${p.primaryPressed}`,
      borderFocusPrimary: `1px solid ${p.primaryHover}`,
      borderDisabledPrimary: `1px solid ${p.controlDisabledBorder}`,
      colorDisabledInfo: p.controlDisabledSurface,
      colorDisabledSuccess: p.controlDisabledSurface,
      colorDisabledWarning: p.controlDisabledSurface,
      colorDisabledError: p.controlDisabledSurface,
      textColorDisabledInfo: p.controlDisabledText,
      textColorDisabledSuccess: p.controlDisabledText,
      textColorDisabledWarning: p.controlDisabledText,
      textColorDisabledError: p.controlDisabledText,
      borderDisabledInfo: `1px solid ${p.controlDisabledBorder}`,
      borderDisabledSuccess: `1px solid ${p.controlDisabledBorder}`,
      borderDisabledWarning: `1px solid ${p.controlDisabledBorder}`,
      borderDisabledError: `1px solid ${p.controlDisabledBorder}`,
    },
    Input: {
      color: p.surface,
      colorDisabled: p.controlDisabledSurface,
      colorFocus: p.surface,
      textColor: p.text,
      textColorDisabled: p.controlDisabledText,
      placeholderColor: p.textPlaceholder,
      placeholderColorDisabled: p.controlDisabledText,
      border: `1px solid ${p.border}`,
      borderHover: `1px solid ${p.borderHover}`,
      borderDisabled: `1px solid ${p.controlDisabledBorder}`,
      borderFocus: `1px solid ${p.borderFocus}`,
      boxShadowFocus: `0 0 0 2px ${p.focusShadow}`,
    },
    Menu: {
      itemColorActive: p.surfacePressed,
      itemColorActiveHover: p.surfaceActiveHover,
      itemColorHover: p.surfaceMuted,
      itemTextColor: p.text,
      itemTextColorHover: p.textStrong,
      itemTextColorActive: p.textStrong,
      itemTextColorActiveHover: p.textStrong,
      itemIconColor: p.textSecondary,
      itemIconColorHover: p.textStrong,
      itemIconColorActive: p.textStrong,
      itemIconColorActiveHover: p.textStrong,
    },
    Tabs: {
      tabTextColorActiveLine: p.text,
      tabTextColorHoverLine: p.text,
      barColor: p.text,
    },
    Card: {
      color: p.surface,
      colorEmbedded: p.surfaceMuted,
      borderColor: p.border,
    },
    Drawer: {
      color: p.surface,
    },
    Modal: {
      color: p.surfaceElevated,
    },
  }
}
